apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "datafactory.labels" . | nindent 4 }}
  name: {{ template "datafactory.fullname" . }}-config
data:
  application.yml: |
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/application.yml" | nindent 4 }}
  {{ end }}
