spring:
  application:
    name: azure-datafactory

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /docs

graph:
  tenantId: ${GRAPH_TENANT_ID}
  clientId: ${GRAPH_CLIENT_ID}
  clientSecret: ${GRAPH_CLIENT_SECRET}

permission:
  customRoleDefinitionId: ""
