spring:
  application:
    name: azure-datafactory

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /docs

graph:
  tenantId: ${GRAPH_TENANT_ID}
  clientId: ${GRAPH_CLIENT_ID}
  clientSecret: ${GRAPH_CLIENT_SECRET}

permission:
  customRoleDefinitionId: ""

powershell:
  waitPause: 10
  maxWait: 50000
  tempFolder: "/tmp"

git:
  azureDevOps:
    username: ${GIT_AZURE_USERNAME}
    password: ${GIT_AZURE_PASSWORD}
    accountName: ""
    collaborationBranch: ""
    rootFolder: ""
    lastCommitId: ""
    tenantId: ""
    disablePublish: true

misc:
  developmentEnvironmentName: ""
